def socket_test():
  set_standard_analog_input_domain(0, 1)
  set_standard_analog_input_domain(1, 1)
  set_tool_analog_input_domain(0, 1)
  set_tool_analog_input_domain(1, 1)
  set_analog_outputdomain(0, 0)
  set_analog_outputdomain(1, 0)
  set_tool_voltage(24)
  set_input_actions_to_default()
  set_safety_mode_transition_hardness(1)
  set_tool_communication(False, 115200, 0, 1, 1.5, 3.5)
  set_tool_output_mode(0)
  set_tool_digital_output_mode(0, 1)
  set_tool_digital_output_mode(1, 1)
  set_tcp(p[0.0,0.0,0.0,0.0,0.0,0.0])
  set_payload(0.0)
  set_gravity([0.0, 0.0, 9.82])
  global Left=p[-6.94355024838389E-7,-0.3573830725550047,0.5718008425121736,1.2089410868386634,1.2094433911501887,1.2088961085928163]
  global Plane_1=p[1.8682271822079773E-5,-0.23303479558178586,0.9513305074298288,-1.5711204892335713,-1.825501810477879E-4,1.0073763764349345E-4]
  global Point_1=p[-1.2046794464204424E-5,-0.23342744854025702,0.525722560961498,0.007905132799289517,-1.5971338779121678,0.008108905796291827]
  global Right=p[-1.824910988089401E-5,-0.23342348399103727,0.5271515851823937,-1.2092318693058517,-1.2091554166629959,1.2092387994943108]
  # begin: URCap Installation Node
  #   Source: External Control, 1.0.1, FZI Research Center for Information Technology
  #   Type: External Control
  # end: URCap Installation Node
  $ 1 "BeforeStart"
  $ 2 "var_1≔socket_open('192.168.56.1',30000)"
  global var_1=socket_open("192.168.56.1",30000)
  while (True):
    $ 3 "Robot Program"
    $ 4 "Loop (var_1≟ False )"
    while ((var_1 ==   False  )):
      $ 5 "var_1≔socket_open('192.168.56.1',30000)"
      global var_1=socket_open("192.168.56.1",30000)
      $ 6 "Wait: 0.5"
      sleep(0.5)
    end
    $ 7 "pose1≔get_actual_tcp_pose()"
    global pose1=get_actual_tcp_pose()
    $ 8 "joints1≔get_actual_joint_positions()"
    global joints1=get_actual_joint_positions()
    $ 9 "socket_send_string(pose1)"
    socket_send_string(pose1)
    $ 10 "Wait: 0.5"
    sleep(0.5)
    $ 11 "socket_send_string(joints1)"
    socket_send_string(joints1)
    $ 12 "Wait: 0.5"
    sleep(0.5)
    $ 13 "socket_send_string('asking_for_data')"
    socket_send_string("asking_for_data")
    $ 14 "Wait: 0.5"
    sleep(0.5)
    $ 15 "var_2≔socket_read_ascii_float(3)"
    global var_2=socket_read_ascii_float(3)
    $ 16 "Wait: 0.5"
    sleep(0.5)
    $ 17 "var_1≔ False "
    global var_1=  False  
    $ 18 "socket_close()"
    socket_close()
  end
end
